---
- name: Install Nginx
  ansible.builtin.apt:
    pkg:
      - nginx
    state: latest
    update_cache: true

- name: Set main config for Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when: "ansible_service_mgr == 'systemd'" 
  register: nginx_main_conf

- name: Set miniolb.conf for Nginx
  template:
    src: miniolb.conf.j2
    dest: /etc/nginx/conf.d/miniolb.conf
  when: "ansible_service_mgr == 'systemd'" 
  register: nginx_miniolb_conf

- name: Debug groups
  debug:
    msg: "{{  groups['minio_cluster_hosts']  }}"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  when: (nginx_main_conf.changed) or
        (nginx_miniolb_conf.changed)
