---
- name: Add the group 'minio'
  ansible.builtin.group:
    name: minio-user
    state: present

- name: Add the user 'minio'
  ansible.builtin.user:
    name: minio-user
    group: minio-user
    comment: minio-user
    shell: /sbin/nologin

- name: Creates directory minio mount
  ansible.builtin.file:
    path: /s3/minio-{{ item }}
    owner: minio-user
    group: minio-user
    state: directory
  loop:
    - 0
    - 1
    - 2
    - 3

- name: Parted minio Disks
  community.general.parted:
    device: /dev/{{ item }}
    number: 1
    flags: [lvm]
    state: present
  loop:
    - vdb
    - vdc
    - vdd
    - vde

- name: Format mino Disks
  community.general.filesystem:
    fstype: xfs
    dev: /dev/{{ item }}1
  loop:
    - vdb
    - vdc
    - vdd
    - vde

- name: Mount minio Disks
  ansible.posix.mount:
    path: /s3/minio-{{ item.group }}
    src: /dev/{{ item.name}}1
    fstype: xfs
    state: mounted
  loop:
    - { name: 'vdb', group: '0'}
    - { name: 'vdc', group: '1'}
    - { name: 'vdd', group: '2'}
    - { name: 'vde', group: '3'}

- name: Copy minio file
  ansible.builtin.copy:
    src: ../files/minio
    dest: /usr/local/bin/minio
    owner: minio-user
    group: minio-user
    mode: '0744'

- name: Creates minio directory config
  ansible.builtin.file:
    path: /etc/minio
    owner: minio-user
    group: minio-user
    state: directory

- name: Creates minio ENV file
  ansible.builtin.template:
    src: minio.env.j2
    dest: /etc/default/minio
    owner: minio-user
    group: minio-user
  when: "ansible_service_mgr == 'systemd'" 
  register: minio_env

- name: Creates minio systemd file
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service

- name: Make sure a service minio is running and enabled
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    enabled: true
    name: minio

- name: Restart minio if ENV was changed
  ansible.builtin.systemd_service:  
    state: restarted
    name: minio
  when: minio_env.changed
