---
- name: Install required system packages
  apt:
    pkg:
      - bind9
      - dnsutils
    state: latest
    update_cache: true

- name: Set main config file named.conf
  template:
    src: named.conf.j2
    dest: /etc/bind/named.conf

- name: Set bind9 config options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    mode: preserve

- name: Creates directory for Master BIND
  ansible.builtin.file:
    path: /etc/bind/master-zones
    state: directory

- name: Set Master Fanat BIND
  template:
    src: fanat.home.j2
    dest: /etc/bind/master-zones/fanat.home
    mode: preserve

- name: Set log file
  template:
    src: log.conf.j2
    dest: /etc/bind/log.conf

- name: Restart bind9
  service:
    name: bind9
    state: restarted
    enabled: true