apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-deployments
  labels:
    app: home-assistant-k8s
    owner: fanat
  namespace: home-assistant
spec:
  replicas: 3
  selector:
    matchLabels:
      project: fanat-ha
  template:
    metadata:
      labels: 
        project: fanat-ha
    spec:
      containers:
        - name: container-home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: home-assistant-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home-assistant-deployments
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50