apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres-deployment
 labels:
   app: postgres
spec:
 replicas: 1
 selector:
   matchLabels:
     app: postgres
 template:
   metadata:
     labels:
       app: postgres
   spec:
      containers:
      - name: postgres        
        image: postgres:14
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
             secretKeyRef:
               name: postgres-secret
               key: password
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
          - name: postgres-volume-mount
            mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
              - bash
              - "-c"
              - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
          initialDelaySeconds: 15
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
              - bash
              - "-c"
              - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
          initialDelaySeconds: 15
          timeoutSeconds: 2
      nodeSelector:
        app: postgres
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pv-claim
 strategy:
   type: RollingUpdate
