- name: Play configure DNS server
  hosts: dns_hosts
  become: true
  vars:
    local_network: "192.168.1.0/24"
    dns_ip: "192.168.1.2"
    fanat_ubuntu_test_ip: "192.168.1.177"
    home_assistant_ip: "192.168.1.128"
    proxmox_ip: "192.168.1.176"
  tasks:
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow
  roles:
    - dns
    - prereq

