---
- name: Set timezone Moscow
  hosts: minio_cluster_hosts
  become: true
  tasks:
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow

- name: Install minio_cluster
  hosts: minio_cluster_hosts
  become: true
  roles:
    - prereq
    - minio_cluster
    - minio_cluster_lb
    - keepalivedvip
