---
- name: Install required system packages
  hosts: fanat-ubuntu-test
  become: true
  tasks:
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow
  roles:
   - prereq
