---
- name: Install required system packages
  hosts: all
  become: true
  tasks:
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow
  roles:
    - prereq
