---
- name: Install Nginx
  ansible.builtin.apt:
    pkg:
      - nginx
    state: latest
    update_cache: true

- name: Set main config for Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when: "ansible_service_mgr == 'systemd'" 
  register: nginx_main_conf

- name: Set proxmox.conf for Nginx
  template:
    src: proxmox.conf.j2
    dest: /etc/nginx/conf.d/proxmox.conf
  when: "ansible_service_mgr == 'systemd'" 
  register: nginx_proxmox_conf

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  when: (nginx_main_conf.changed) or
        (nginx_proxmox_conf.changed)
