apiVersion: v1
kind: Pod
metadata:
  name: home-assistant
  labels:
    env   : home
    owner : Fanat
spec:
  containers:
    - name: container-home-assistant
      image: ghcr.io/home-assistant/home-assistant:stable
      ports:
        - containerPort: 8123