---
- name: Install required system packages
  apt:
    pkg:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - bluez
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - zlib1g-dev
      - autoconf
      - build-essential
      - libopenjp2-7
      - libtiff5
      - libturbojpeg0-dev
      - tzdata
      - ffmpeg
      - liblapack3
      - liblapack-dev
      - libatlas-base-dev
    state: latest
    update_cache: true

- name: Ensure group "homeassistant" exists
  group:
    name: homeassistant
    state: present

- name: Ensure user "homeassistant" exists
  user:
    name: homeassistant
    comment: Home Assistant
    group: homeassistant

- name: Creates directory for Home Assistant VIRTUAL ENVIRONMENT
  file:
    path: /srv/homeassistant
    owner: homeassistant
    group: homeassistant
    state: directory

- name: Create virtual environment
  become: true
  become_method: enable
  become_user: homeassistant
  command: python3 -m venv /srv/homeassistant

- name: Activate virtual environment
  become: true
  become_method: enable
  become_user: homeassistant
  shell: source /srv/homeassistant/bin/activate

- name: Install required packages
  become: true
  become_method: enable
  become_user: homeassistant
  shell: python3 -m pip install wheel
  args:
    chdir: /srv/homeassistant

- name: Install Home Assistant Core
  become: true
  become_method: enable
  become_user: homeassistant
  shell: pip3 install homeassistant==2024.1.5
  args:
    chdir: /srv/homeassistant

- name: Deactivate virtual environment
  shell: deactivate