apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
      # Раскомментируйте следующую строку, если используете NodePort и задали его в values.yaml
      # nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-nginx